import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Chance Collective",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`antialiased bg-[#F1F5F9]`}
      >
        <ReduxProvider>
          {children}

          <ToastContainer />
        </ReduxProvider>
      </body>
    </html>
  );
}
